### ISSUE TITLE
Implement  part of  video consultation service

### ISSUE THREAD

**Issue by ShiqiDing** [GoldWaterFall/Chat-Health#7]
I found that the TRTC video consultation function of this project has not been completed, so I want to implement this function. My initial ideas include:
1. Realize the basic services of TRTC consultation
2. Realize the functions and processes for doctors to go online on the doctor's web side, enable registration consultation, video consultation, and query patient information.
3. Realize the function of patients submitting video consultation applications, paying consultation fees, and receiving video consultations on the patient applet.
I hope that I can refine the specific details after communicating with the team. I very much hope that you can assign this task to me.

**Comment by GoldWaterFall** [comment]
Thank you very much for your support! If you are willing to do this part of the function, I hope you can submit a PR after completion. We will decide whether to adopt your suggestion after review. Thank you again for your support!

**Comment by ShiqiDing** [comment]
Wow! I will work hard to implement this function. Thank you for your timely reply. I hope to continue to communicate with you in the subsequent development process.

**Comment by GoldWaterFall** [comment]
Hi Shiqi, I have sorted out the logic of the entire TRTC part. You can do part of it, because some parts are very challenging. Of course, you can also complete them all. The approximate content that needs to be achieved is as follows:
1. Realize online and offline doctors on the web side
2. Enable or close video consultation registration
3. Use restfulAPI to encapsulate the list of departments and clinics
4. Use Picker to implement conditional query for online doctors
5. Load the online doctor list on the patient side
6. Use restful package to create video consultation registration form
7. Check the registered payment results
8. Use websocket to send notification messages
9. Use restful to encapsulate the query information interface
10. The MIS system actively loads consultation information
This is what I think of at the moment. You can also add some of your ideas. You only need to complete the back-end part. 1&2. I see that you have implemented it and submitted the PR. I will verify it as soon as possible. Hope your development goes well!

**Comment by ShiqiDing** [comment]
Okay, I'll try my best to do it

**Comment by ShiqiDing** [comment]
I decided to do three functions 1, 2 and 6
